Develop fix model dai
y-ogawara/01-Spica-Android pull request #170
Opened 2019-02-09 13:54 UTC by Dai1678

## Overview (このPRでなにをやってるのかの説明)
- ScriptModel, SpicaBlockを削除し、BlockModel, UIBlockModelに置き換え
- 使用していないBlockSelectActivity, BlockDetailActivityの削除、同xmlのrename
- SpicaBlockで何のブロックか判定していたものをBlockクラスにて行うようにした
- 固定値はConfigクラスで管理するように変更
- specialScriptなどの○ァックな命名のものを修正
- if文で3分岐以上あるコードで可能なものをswitch文に変更
- ブロックのクリック処理で同じコードが散見されていたので、別メソッドに定義
- 使用していないメソッドに削除or@Deprecatedをつけた
- warning出ているものを極力修正
- コードフォーマット

## Issue (解決するissueのリンクがあれば貼る)
- #166

2019-02-09 14:07 UTC, y-ogawara requested changes
途中であきらめた

2019-02-09 14:07 UTC, y-ogawara commented on app/src/main/java/com/t_robop/yuusuke/a01_spica_android/Block.java
>      // TODO こんな感じの実装がしたい
TODO 残ってるけど

2019-02-09 14:07 UTC, y-ogawara commented on app/src/main/java/com/t_robop/yuusuke/a01_spica_android/Block.java
> +        public static final String id = "02";
🤔

2019-02-09 14:07 UTC, y-ogawara commented on app/src/main/java/com/t_robop/yuusuke/a01_spica_android/UI/Script/ScriptContract.java
> -        /**
これ治す必要なくね

2019-02-09 14:12 UTC, Dai1678 commented on app/src/main/java/com/t_robop/yuusuke/a01_spica_android/Block.java
>      // TODO こんな感じの実装がしたい
まだ仕様詰めたいので、ここの拡張は別PRで。

2019-02-09 14:15 UTC, Dai1678 commented on app/src/main/java/com/t_robop/yuusuke/a01_spica_android/UI/Script/ScriptContract.java
> -        /**
スコープ内でこの書き方すると ```/**```の ```*```が一個余計っていうIDE判定でwarningがめちゃくちゃ出てたので治してしまった。

行数稼ぎすぎな感じが否めないので ```//```で良いのではとも思う。

2019-03-03 05:20 UTC, Dai1678 commented
PRでかすぎるのでCLose

2019-03-03 05:20 UTC, closed without merging