fix detail-fragment
y-ogawara/01-Spica-Android pull request #194
Opened 2019-03-03 09:49 UTC by TaigaNatto

## Overview (このPRでなにをやってるのかの説明)
- `DetailFragment` 内のラジオボタンの間隔を広く
- `DetailFragment` の「ほぞん」「すてる」を横並びに

## Issue (解決するissueのリンクがあれば貼る)
- #182 
- #183

2019-03-03 09:50 UTC, TaigaNatto commented
@Dai1678 タブで実行したら案外入るから横並びで実装してみた

2019-03-03 12:43 UTC, Dai1678 commented
見やすいように変更後スクショ上げとく

<img width="1284" alt="2019-03-03 21 41 35" src="https://user-images.githubusercontent.com/19250035/53695314-36632c00-3dfd-11e9-9a87-76b19d78e440.png">
<img width="1284" alt="2019-03-03 21 41 46" src="https://user-images.githubusercontent.com/19250035/53695315-36fbc280-3dfd-11e9-9791-bc9dacda5500.png">
<img width="1284" alt="2019-03-03 21 41 53" src="https://user-images.githubusercontent.com/19250035/53695316-36fbc280-3dfd-11e9-9b53-f9b19f5591a4.png">

2019-03-03 13:05 UTC, Dai1678 commented
個人的には、
シークバーとラジオボタンとの間隔、速度選択のラジオボタンと左右回転選択のラジオボタンとの間隔もせまいかなーと感じるけどどうだろう..
必要ならFragmentの縦幅ちょっと長くして上記の間隔調整してみてもいいのでは

すてるボタンとほぞんボタンはこれで良いと思います

2019-03-03 13:41 UTC, TaigaNatto commented
たしかにタブだとまだいけそうだね
やってみる

2019-03-03 14:54 UTC, y-ogawara commented
@TaigaNatto 進むのとき，速度選択はもう少し下にあるべきかなーと思う．たぶん回転時のレイアウトに合わせてると思うんだけど，違和感ある．もしもの時も同じく
タッチイベントの反応は良くなったと思う．

あとは，もしもの時の選択が下の方だから，間違えて閉じちゃいそう，閉じる範囲を本当はもう少し外側にしたい

LGで検証しました

2019-03-04 16:06 UTC, multiverse2011 requested changes
marginとるのどうなったん？

2019-03-06 04:54 UTC, y-ogawara commented
@TaigaNatto

2019-03-06 15:43 UTC, y-ogawara commented
@TaigaNatto レビュー以前にコンフリクトしてるマン

2019-03-07 07:49 UTC, y-ogawara approved these changes
LGTM

2019-03-07 23:10 UTC, merged