add firebase-analytics log-system
y-ogawara/01-Spica-Android pull request #200
Opened 2019-03-06 14:51 UTC by TaigaNatto

## Overview (このPRでなにをやってるのかの説明)
- `Firebase Analytics` でログを発火するようにしました。
- 全てのログで最低限ipアドレスを持つようにしています。
- 現在は下記のタイミングでログを発火します。
```
- Runボタンクリック時
- 設定画面遷移時
- 復元ボタン発動時
```

## Link
Firebase-console
- https://console.firebase.google.com/project/spica-android-65bef/analytics/app/android:com.t_robop.yuusuke.a01_spica_android/debugview%3Ft=2&cs=app.m.debugview.overview&g=1

リアルタイムなログはデバッグビューで確認できます。
- https://support.google.com/firebase/answer/7201382?hl=ja&utm_id=ad

2019-03-06 15:41 UTC, y-ogawara requested changes
.idea/gradle.xmlはいらないよー

2019-03-07 07:48 UTC, y-ogawara commented
ソースコード的に問題はなさそう
@TaigaNatto 動作検証済み？

2019-03-07 15:49 UTC, Dai1678 commented
@TaigaNatto 
Runボタン押されたときに、UDPで送られるコマンドをログに入れておかないと意味ないのでは。
ユーザーが何したのか一番わかるところなので。

2019-03-07 15:51 UTC, Dai1678 commented
アナリティクスのデバッグモード起動してfirebaseにログアップロードされていること確認しました。
Kindleで動作確認。

2019-03-07 21:44 UTC, TaigaNatto commented
それ思ったけど、毎回全部送ると挙動エグいことになりそうかもってのと、まだ試験運用だから最低限これがあればいいかなってのを実装してある。
パッと思いついてすぐ書けそうなのだけ書いた感じだから、イベントで必要なログが思いついたら随時更新して

2019-03-07 23:10 UTC, y-ogawara commented
とりあえず動くん？ @TaigaNatto

2019-03-07 23:14 UTC, merged